// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication.proto

package edu.uconn.guarddogs.guardthebridge;

public final class Communication {
  private Communication() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 nReqId = 1;
    boolean hasNReqId();
    int getNReqId();
    
    // required string sReqType = 2;
    boolean hasSReqType();
    String getSReqType();
    
    // optional int32 nCarId = 3;
    boolean hasNCarId();
    int getNCarId();
    
    // repeated string sParams = 4;
    java.util.List<String> getSParamsList();
    int getSParamsCount();
    String getSParams(int index);
    
    // repeated int32 nParams = 5 [packed = true];
    java.util.List<java.lang.Integer> getNParamsList();
    int getNParamsCount();
    int getNParams(int index);
    
    // optional int32 nClient = 6;
    boolean hasNClient();
    int getNClient();
    
    // optional .PatronList plPatronList = 7;
    boolean hasPlPatronList();
    edu.uconn.guarddogs.guardthebridge.Patron.PatronList getPlPatronList();
    edu.uconn.guarddogs.guardthebridge.Patron.PatronListOrBuilder getPlPatronListOrBuilder();
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(Builder builder) {
      super(builder);
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.uconn.guarddogs.guardthebridge.Communication.internal_static_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.uconn.guarddogs.guardthebridge.Communication.internal_static_Request_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 nReqId = 1;
    public static final int NREQID_FIELD_NUMBER = 1;
    private int nReqId_;
    public boolean hasNReqId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getNReqId() {
      return nReqId_;
    }
    
    // required string sReqType = 2;
    public static final int SREQTYPE_FIELD_NUMBER = 2;
    private java.lang.Object sReqType_;
    public boolean hasSReqType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getSReqType() {
      java.lang.Object ref = sReqType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sReqType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSReqTypeBytes() {
      java.lang.Object ref = sReqType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sReqType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 nCarId = 3;
    public static final int NCARID_FIELD_NUMBER = 3;
    private int nCarId_;
    public boolean hasNCarId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getNCarId() {
      return nCarId_;
    }
    
    // repeated string sParams = 4;
    public static final int SPARAMS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList sParams_;
    public java.util.List<String>
        getSParamsList() {
      return sParams_;
    }
    public int getSParamsCount() {
      return sParams_.size();
    }
    public String getSParams(int index) {
      return sParams_.get(index);
    }
    
    // repeated int32 nParams = 5 [packed = true];
    public static final int NPARAMS_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Integer> nParams_;
    public java.util.List<java.lang.Integer>
        getNParamsList() {
      return nParams_;
    }
    public int getNParamsCount() {
      return nParams_.size();
    }
    public int getNParams(int index) {
      return nParams_.get(index);
    }
    private int nParamsMemoizedSerializedSize = -1;
    
    // optional int32 nClient = 6;
    public static final int NCLIENT_FIELD_NUMBER = 6;
    private int nClient_;
    public boolean hasNClient() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getNClient() {
      return nClient_;
    }
    
    // optional .PatronList plPatronList = 7;
    public static final int PLPATRONLIST_FIELD_NUMBER = 7;
    private edu.uconn.guarddogs.guardthebridge.Patron.PatronList plPatronList_;
    public boolean hasPlPatronList() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public edu.uconn.guarddogs.guardthebridge.Patron.PatronList getPlPatronList() {
      return plPatronList_;
    }
    public edu.uconn.guarddogs.guardthebridge.Patron.PatronListOrBuilder getPlPatronListOrBuilder() {
      return plPatronList_;
    }
    
    private void initFields() {
      nReqId_ = 0;
      sReqType_ = "";
      nCarId_ = 0;
      sParams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      nParams_ = java.util.Collections.emptyList();;
      nClient_ = 0;
      plPatronList_ = edu.uconn.guarddogs.guardthebridge.Patron.PatronList.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNReqId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSReqType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, nReqId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSReqTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, nCarId_);
      }
      for (int i = 0; i < sParams_.size(); i++) {
        output.writeBytes(4, sParams_.getByteString(i));
      }
      if (getNParamsList().size() > 0) {
        output.writeRawVarint32(42);
        output.writeRawVarint32(nParamsMemoizedSerializedSize);
      }
      for (int i = 0; i < nParams_.size(); i++) {
        output.writeInt32NoTag(nParams_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(6, nClient_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(7, plPatronList_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, nReqId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSReqTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, nCarId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sParams_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(sParams_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getSParamsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < nParams_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(nParams_.get(i));
        }
        size += dataSize;
        if (!getNParamsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        nParamsMemoizedSerializedSize = dataSize;
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, nClient_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, plPatronList_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.uconn.guarddogs.guardthebridge.Communication.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.uconn.guarddogs.guardthebridge.Communication.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.uconn.guarddogs.guardthebridge.Communication.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.uconn.guarddogs.guardthebridge.Communication.internal_static_Request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.uconn.guarddogs.guardthebridge.Communication.internal_static_Request_fieldAccessorTable;
      }
      
      // Construct using edu.uconn.guarddogs.guardthebridge.Communication.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlPatronListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        nReqId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sReqType_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        nCarId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        sParams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        nParams_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000010);
        nClient_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (plPatronListBuilder_ == null) {
          plPatronList_ = edu.uconn.guarddogs.guardthebridge.Patron.PatronList.getDefaultInstance();
        } else {
          plPatronListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.uconn.guarddogs.guardthebridge.Communication.Request.getDescriptor();
      }
      
      public edu.uconn.guarddogs.guardthebridge.Communication.Request getDefaultInstanceForType() {
        return edu.uconn.guarddogs.guardthebridge.Communication.Request.getDefaultInstance();
      }
      
      public edu.uconn.guarddogs.guardthebridge.Communication.Request build() {
        edu.uconn.guarddogs.guardthebridge.Communication.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.uconn.guarddogs.guardthebridge.Communication.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.uconn.guarddogs.guardthebridge.Communication.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.uconn.guarddogs.guardthebridge.Communication.Request buildPartial() {
        edu.uconn.guarddogs.guardthebridge.Communication.Request result = new edu.uconn.guarddogs.guardthebridge.Communication.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nReqId_ = nReqId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sReqType_ = sReqType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.nCarId_ = nCarId_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          sParams_ = new com.google.protobuf.UnmodifiableLazyStringList(
              sParams_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.sParams_ = sParams_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          nParams_ = java.util.Collections.unmodifiableList(nParams_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.nParams_ = nParams_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000008;
        }
        result.nClient_ = nClient_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000010;
        }
        if (plPatronListBuilder_ == null) {
          result.plPatronList_ = plPatronList_;
        } else {
          result.plPatronList_ = plPatronListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.uconn.guarddogs.guardthebridge.Communication.Request) {
          return mergeFrom((edu.uconn.guarddogs.guardthebridge.Communication.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.uconn.guarddogs.guardthebridge.Communication.Request other) {
        if (other == edu.uconn.guarddogs.guardthebridge.Communication.Request.getDefaultInstance()) return this;
        if (other.hasNReqId()) {
          setNReqId(other.getNReqId());
        }
        if (other.hasSReqType()) {
          setSReqType(other.getSReqType());
        }
        if (other.hasNCarId()) {
          setNCarId(other.getNCarId());
        }
        if (!other.sParams_.isEmpty()) {
          if (sParams_.isEmpty()) {
            sParams_ = other.sParams_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureSParamsIsMutable();
            sParams_.addAll(other.sParams_);
          }
          onChanged();
        }
        if (!other.nParams_.isEmpty()) {
          if (nParams_.isEmpty()) {
            nParams_ = other.nParams_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureNParamsIsMutable();
            nParams_.addAll(other.nParams_);
          }
          onChanged();
        }
        if (other.hasNClient()) {
          setNClient(other.getNClient());
        }
        if (other.hasPlPatronList()) {
          mergePlPatronList(other.getPlPatronList());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNReqId()) {
          
          return false;
        }
        if (!hasSReqType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              nReqId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sReqType_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              nCarId_ = input.readInt32();
              break;
            }
            case 34: {
              ensureSParamsIsMutable();
              sParams_.add(input.readBytes());
              break;
            }
            case 40: {
              ensureNParamsIsMutable();
              nParams_.add(input.readInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addNParams(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              nClient_ = input.readInt32();
              break;
            }
            case 58: {
              edu.uconn.guarddogs.guardthebridge.Patron.PatronList.Builder subBuilder = edu.uconn.guarddogs.guardthebridge.Patron.PatronList.newBuilder();
              if (hasPlPatronList()) {
                subBuilder.mergeFrom(getPlPatronList());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPlPatronList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 nReqId = 1;
      private int nReqId_ ;
      public boolean hasNReqId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getNReqId() {
        return nReqId_;
      }
      public Builder setNReqId(int value) {
        bitField0_ |= 0x00000001;
        nReqId_ = value;
        onChanged();
        return this;
      }
      public Builder clearNReqId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nReqId_ = 0;
        onChanged();
        return this;
      }
      
      // required string sReqType = 2;
      private java.lang.Object sReqType_ = "";
      public boolean hasSReqType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getSReqType() {
        java.lang.Object ref = sReqType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sReqType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSReqType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sReqType_ = value;
        onChanged();
        return this;
      }
      public Builder clearSReqType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sReqType_ = getDefaultInstance().getSReqType();
        onChanged();
        return this;
      }
      void setSReqType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        sReqType_ = value;
        onChanged();
      }
      
      // optional int32 nCarId = 3;
      private int nCarId_ ;
      public boolean hasNCarId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getNCarId() {
        return nCarId_;
      }
      public Builder setNCarId(int value) {
        bitField0_ |= 0x00000004;
        nCarId_ = value;
        onChanged();
        return this;
      }
      public Builder clearNCarId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nCarId_ = 0;
        onChanged();
        return this;
      }
      
      // repeated string sParams = 4;
      private com.google.protobuf.LazyStringList sParams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSParamsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          sParams_ = new com.google.protobuf.LazyStringArrayList(sParams_);
          bitField0_ |= 0x00000008;
         }
      }
      public java.util.List<String>
          getSParamsList() {
        return java.util.Collections.unmodifiableList(sParams_);
      }
      public int getSParamsCount() {
        return sParams_.size();
      }
      public String getSParams(int index) {
        return sParams_.get(index);
      }
      public Builder setSParams(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSParamsIsMutable();
        sParams_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addSParams(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSParamsIsMutable();
        sParams_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllSParams(
          java.lang.Iterable<String> values) {
        ensureSParamsIsMutable();
        super.addAll(values, sParams_);
        onChanged();
        return this;
      }
      public Builder clearSParams() {
        sParams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      void addSParams(com.google.protobuf.ByteString value) {
        ensureSParamsIsMutable();
        sParams_.add(value);
        onChanged();
      }
      
      // repeated int32 nParams = 5 [packed = true];
      private java.util.List<java.lang.Integer> nParams_ = java.util.Collections.emptyList();;
      private void ensureNParamsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          nParams_ = new java.util.ArrayList<java.lang.Integer>(nParams_);
          bitField0_ |= 0x00000010;
         }
      }
      public java.util.List<java.lang.Integer>
          getNParamsList() {
        return java.util.Collections.unmodifiableList(nParams_);
      }
      public int getNParamsCount() {
        return nParams_.size();
      }
      public int getNParams(int index) {
        return nParams_.get(index);
      }
      public Builder setNParams(
          int index, int value) {
        ensureNParamsIsMutable();
        nParams_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addNParams(int value) {
        ensureNParamsIsMutable();
        nParams_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllNParams(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureNParamsIsMutable();
        super.addAll(values, nParams_);
        onChanged();
        return this;
      }
      public Builder clearNParams() {
        nParams_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      
      // optional int32 nClient = 6;
      private int nClient_ ;
      public boolean hasNClient() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getNClient() {
        return nClient_;
      }
      public Builder setNClient(int value) {
        bitField0_ |= 0x00000020;
        nClient_ = value;
        onChanged();
        return this;
      }
      public Builder clearNClient() {
        bitField0_ = (bitField0_ & ~0x00000020);
        nClient_ = 0;
        onChanged();
        return this;
      }
      
      // optional .PatronList plPatronList = 7;
      private edu.uconn.guarddogs.guardthebridge.Patron.PatronList plPatronList_ = edu.uconn.guarddogs.guardthebridge.Patron.PatronList.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.uconn.guarddogs.guardthebridge.Patron.PatronList, edu.uconn.guarddogs.guardthebridge.Patron.PatronList.Builder, edu.uconn.guarddogs.guardthebridge.Patron.PatronListOrBuilder> plPatronListBuilder_;
      public boolean hasPlPatronList() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronList getPlPatronList() {
        if (plPatronListBuilder_ == null) {
          return plPatronList_;
        } else {
          return plPatronListBuilder_.getMessage();
        }
      }
      public Builder setPlPatronList(edu.uconn.guarddogs.guardthebridge.Patron.PatronList value) {
        if (plPatronListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          plPatronList_ = value;
          onChanged();
        } else {
          plPatronListBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder setPlPatronList(
          edu.uconn.guarddogs.guardthebridge.Patron.PatronList.Builder builderForValue) {
        if (plPatronListBuilder_ == null) {
          plPatronList_ = builderForValue.build();
          onChanged();
        } else {
          plPatronListBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder mergePlPatronList(edu.uconn.guarddogs.guardthebridge.Patron.PatronList value) {
        if (plPatronListBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              plPatronList_ != edu.uconn.guarddogs.guardthebridge.Patron.PatronList.getDefaultInstance()) {
            plPatronList_ =
              edu.uconn.guarddogs.guardthebridge.Patron.PatronList.newBuilder(plPatronList_).mergeFrom(value).buildPartial();
          } else {
            plPatronList_ = value;
          }
          onChanged();
        } else {
          plPatronListBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder clearPlPatronList() {
        if (plPatronListBuilder_ == null) {
          plPatronList_ = edu.uconn.guarddogs.guardthebridge.Patron.PatronList.getDefaultInstance();
          onChanged();
        } else {
          plPatronListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronList.Builder getPlPatronListBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getPlPatronListFieldBuilder().getBuilder();
      }
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronListOrBuilder getPlPatronListOrBuilder() {
        if (plPatronListBuilder_ != null) {
          return plPatronListBuilder_.getMessageOrBuilder();
        } else {
          return plPatronList_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          edu.uconn.guarddogs.guardthebridge.Patron.PatronList, edu.uconn.guarddogs.guardthebridge.Patron.PatronList.Builder, edu.uconn.guarddogs.guardthebridge.Patron.PatronListOrBuilder> 
          getPlPatronListFieldBuilder() {
        if (plPatronListBuilder_ == null) {
          plPatronListBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.uconn.guarddogs.guardthebridge.Patron.PatronList, edu.uconn.guarddogs.guardthebridge.Patron.PatronList.Builder, edu.uconn.guarddogs.guardthebridge.Patron.PatronListOrBuilder>(
                  plPatronList_,
                  getParentForChildren(),
                  isClean());
          plPatronList_ = null;
        }
        return plPatronListBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Request)
    }
    
    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Request)
  }
  
  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 nRespId = 1;
    boolean hasNRespId();
    int getNRespId();
    
    // required string sResValue = 2;
    boolean hasSResValue();
    String getSResValue();
    
    // repeated string sResAdd = 3;
    java.util.List<String> getSResAddList();
    int getSResAddCount();
    String getSResAdd(int index);
    
    // repeated int32 nResAdd = 4 [packed = true];
    java.util.List<java.lang.Integer> getNResAddList();
    int getNResAddCount();
    int getNResAdd(int index);
    
    // optional .PatronList plPatronList = 5;
    boolean hasPlPatronList();
    edu.uconn.guarddogs.guardthebridge.Patron.PatronList getPlPatronList();
    edu.uconn.guarddogs.guardthebridge.Patron.PatronListOrBuilder getPlPatronListOrBuilder();
  }
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(Builder builder) {
      super(builder);
    }
    private Response(boolean noInit) {}
    
    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.uconn.guarddogs.guardthebridge.Communication.internal_static_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.uconn.guarddogs.guardthebridge.Communication.internal_static_Response_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 nRespId = 1;
    public static final int NRESPID_FIELD_NUMBER = 1;
    private int nRespId_;
    public boolean hasNRespId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getNRespId() {
      return nRespId_;
    }
    
    // required string sResValue = 2;
    public static final int SRESVALUE_FIELD_NUMBER = 2;
    private java.lang.Object sResValue_;
    public boolean hasSResValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getSResValue() {
      java.lang.Object ref = sResValue_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sResValue_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSResValueBytes() {
      java.lang.Object ref = sResValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sResValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string sResAdd = 3;
    public static final int SRESADD_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList sResAdd_;
    public java.util.List<String>
        getSResAddList() {
      return sResAdd_;
    }
    public int getSResAddCount() {
      return sResAdd_.size();
    }
    public String getSResAdd(int index) {
      return sResAdd_.get(index);
    }
    
    // repeated int32 nResAdd = 4 [packed = true];
    public static final int NRESADD_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> nResAdd_;
    public java.util.List<java.lang.Integer>
        getNResAddList() {
      return nResAdd_;
    }
    public int getNResAddCount() {
      return nResAdd_.size();
    }
    public int getNResAdd(int index) {
      return nResAdd_.get(index);
    }
    private int nResAddMemoizedSerializedSize = -1;
    
    // optional .PatronList plPatronList = 5;
    public static final int PLPATRONLIST_FIELD_NUMBER = 5;
    private edu.uconn.guarddogs.guardthebridge.Patron.PatronList plPatronList_;
    public boolean hasPlPatronList() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public edu.uconn.guarddogs.guardthebridge.Patron.PatronList getPlPatronList() {
      return plPatronList_;
    }
    public edu.uconn.guarddogs.guardthebridge.Patron.PatronListOrBuilder getPlPatronListOrBuilder() {
      return plPatronList_;
    }
    
    private void initFields() {
      nRespId_ = 0;
      sResValue_ = "";
      sResAdd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      nResAdd_ = java.util.Collections.emptyList();;
      plPatronList_ = edu.uconn.guarddogs.guardthebridge.Patron.PatronList.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNRespId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSResValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, nRespId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSResValueBytes());
      }
      for (int i = 0; i < sResAdd_.size(); i++) {
        output.writeBytes(3, sResAdd_.getByteString(i));
      }
      if (getNResAddList().size() > 0) {
        output.writeRawVarint32(34);
        output.writeRawVarint32(nResAddMemoizedSerializedSize);
      }
      for (int i = 0; i < nResAdd_.size(); i++) {
        output.writeInt32NoTag(nResAdd_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(5, plPatronList_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, nRespId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSResValueBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sResAdd_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(sResAdd_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getSResAddList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < nResAdd_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(nResAdd_.get(i));
        }
        size += dataSize;
        if (!getNResAddList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        nResAddMemoizedSerializedSize = dataSize;
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, plPatronList_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.uconn.guarddogs.guardthebridge.Communication.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Communication.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.uconn.guarddogs.guardthebridge.Communication.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.uconn.guarddogs.guardthebridge.Communication.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.uconn.guarddogs.guardthebridge.Communication.internal_static_Response_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.uconn.guarddogs.guardthebridge.Communication.internal_static_Response_fieldAccessorTable;
      }
      
      // Construct using edu.uconn.guarddogs.guardthebridge.Communication.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlPatronListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        nRespId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sResValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        sResAdd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        nResAdd_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (plPatronListBuilder_ == null) {
          plPatronList_ = edu.uconn.guarddogs.guardthebridge.Patron.PatronList.getDefaultInstance();
        } else {
          plPatronListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.uconn.guarddogs.guardthebridge.Communication.Response.getDescriptor();
      }
      
      public edu.uconn.guarddogs.guardthebridge.Communication.Response getDefaultInstanceForType() {
        return edu.uconn.guarddogs.guardthebridge.Communication.Response.getDefaultInstance();
      }
      
      public edu.uconn.guarddogs.guardthebridge.Communication.Response build() {
        edu.uconn.guarddogs.guardthebridge.Communication.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.uconn.guarddogs.guardthebridge.Communication.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.uconn.guarddogs.guardthebridge.Communication.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.uconn.guarddogs.guardthebridge.Communication.Response buildPartial() {
        edu.uconn.guarddogs.guardthebridge.Communication.Response result = new edu.uconn.guarddogs.guardthebridge.Communication.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nRespId_ = nRespId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sResValue_ = sResValue_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          sResAdd_ = new com.google.protobuf.UnmodifiableLazyStringList(
              sResAdd_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.sResAdd_ = sResAdd_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          nResAdd_ = java.util.Collections.unmodifiableList(nResAdd_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.nResAdd_ = nResAdd_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000004;
        }
        if (plPatronListBuilder_ == null) {
          result.plPatronList_ = plPatronList_;
        } else {
          result.plPatronList_ = plPatronListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.uconn.guarddogs.guardthebridge.Communication.Response) {
          return mergeFrom((edu.uconn.guarddogs.guardthebridge.Communication.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.uconn.guarddogs.guardthebridge.Communication.Response other) {
        if (other == edu.uconn.guarddogs.guardthebridge.Communication.Response.getDefaultInstance()) return this;
        if (other.hasNRespId()) {
          setNRespId(other.getNRespId());
        }
        if (other.hasSResValue()) {
          setSResValue(other.getSResValue());
        }
        if (!other.sResAdd_.isEmpty()) {
          if (sResAdd_.isEmpty()) {
            sResAdd_ = other.sResAdd_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSResAddIsMutable();
            sResAdd_.addAll(other.sResAdd_);
          }
          onChanged();
        }
        if (!other.nResAdd_.isEmpty()) {
          if (nResAdd_.isEmpty()) {
            nResAdd_ = other.nResAdd_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureNResAddIsMutable();
            nResAdd_.addAll(other.nResAdd_);
          }
          onChanged();
        }
        if (other.hasPlPatronList()) {
          mergePlPatronList(other.getPlPatronList());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNRespId()) {
          
          return false;
        }
        if (!hasSResValue()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              nRespId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sResValue_ = input.readBytes();
              break;
            }
            case 26: {
              ensureSResAddIsMutable();
              sResAdd_.add(input.readBytes());
              break;
            }
            case 32: {
              ensureNResAddIsMutable();
              nResAdd_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addNResAdd(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 42: {
              edu.uconn.guarddogs.guardthebridge.Patron.PatronList.Builder subBuilder = edu.uconn.guarddogs.guardthebridge.Patron.PatronList.newBuilder();
              if (hasPlPatronList()) {
                subBuilder.mergeFrom(getPlPatronList());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPlPatronList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 nRespId = 1;
      private int nRespId_ ;
      public boolean hasNRespId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getNRespId() {
        return nRespId_;
      }
      public Builder setNRespId(int value) {
        bitField0_ |= 0x00000001;
        nRespId_ = value;
        onChanged();
        return this;
      }
      public Builder clearNRespId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nRespId_ = 0;
        onChanged();
        return this;
      }
      
      // required string sResValue = 2;
      private java.lang.Object sResValue_ = "";
      public boolean hasSResValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getSResValue() {
        java.lang.Object ref = sResValue_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sResValue_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSResValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sResValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearSResValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sResValue_ = getDefaultInstance().getSResValue();
        onChanged();
        return this;
      }
      void setSResValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        sResValue_ = value;
        onChanged();
      }
      
      // repeated string sResAdd = 3;
      private com.google.protobuf.LazyStringList sResAdd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSResAddIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          sResAdd_ = new com.google.protobuf.LazyStringArrayList(sResAdd_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<String>
          getSResAddList() {
        return java.util.Collections.unmodifiableList(sResAdd_);
      }
      public int getSResAddCount() {
        return sResAdd_.size();
      }
      public String getSResAdd(int index) {
        return sResAdd_.get(index);
      }
      public Builder setSResAdd(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSResAddIsMutable();
        sResAdd_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addSResAdd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSResAddIsMutable();
        sResAdd_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllSResAdd(
          java.lang.Iterable<String> values) {
        ensureSResAddIsMutable();
        super.addAll(values, sResAdd_);
        onChanged();
        return this;
      }
      public Builder clearSResAdd() {
        sResAdd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      void addSResAdd(com.google.protobuf.ByteString value) {
        ensureSResAddIsMutable();
        sResAdd_.add(value);
        onChanged();
      }
      
      // repeated int32 nResAdd = 4 [packed = true];
      private java.util.List<java.lang.Integer> nResAdd_ = java.util.Collections.emptyList();;
      private void ensureNResAddIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          nResAdd_ = new java.util.ArrayList<java.lang.Integer>(nResAdd_);
          bitField0_ |= 0x00000008;
         }
      }
      public java.util.List<java.lang.Integer>
          getNResAddList() {
        return java.util.Collections.unmodifiableList(nResAdd_);
      }
      public int getNResAddCount() {
        return nResAdd_.size();
      }
      public int getNResAdd(int index) {
        return nResAdd_.get(index);
      }
      public Builder setNResAdd(
          int index, int value) {
        ensureNResAddIsMutable();
        nResAdd_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addNResAdd(int value) {
        ensureNResAddIsMutable();
        nResAdd_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllNResAdd(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureNResAddIsMutable();
        super.addAll(values, nResAdd_);
        onChanged();
        return this;
      }
      public Builder clearNResAdd() {
        nResAdd_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      
      // optional .PatronList plPatronList = 5;
      private edu.uconn.guarddogs.guardthebridge.Patron.PatronList plPatronList_ = edu.uconn.guarddogs.guardthebridge.Patron.PatronList.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.uconn.guarddogs.guardthebridge.Patron.PatronList, edu.uconn.guarddogs.guardthebridge.Patron.PatronList.Builder, edu.uconn.guarddogs.guardthebridge.Patron.PatronListOrBuilder> plPatronListBuilder_;
      public boolean hasPlPatronList() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronList getPlPatronList() {
        if (plPatronListBuilder_ == null) {
          return plPatronList_;
        } else {
          return plPatronListBuilder_.getMessage();
        }
      }
      public Builder setPlPatronList(edu.uconn.guarddogs.guardthebridge.Patron.PatronList value) {
        if (plPatronListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          plPatronList_ = value;
          onChanged();
        } else {
          plPatronListBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setPlPatronList(
          edu.uconn.guarddogs.guardthebridge.Patron.PatronList.Builder builderForValue) {
        if (plPatronListBuilder_ == null) {
          plPatronList_ = builderForValue.build();
          onChanged();
        } else {
          plPatronListBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergePlPatronList(edu.uconn.guarddogs.guardthebridge.Patron.PatronList value) {
        if (plPatronListBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              plPatronList_ != edu.uconn.guarddogs.guardthebridge.Patron.PatronList.getDefaultInstance()) {
            plPatronList_ =
              edu.uconn.guarddogs.guardthebridge.Patron.PatronList.newBuilder(plPatronList_).mergeFrom(value).buildPartial();
          } else {
            plPatronList_ = value;
          }
          onChanged();
        } else {
          plPatronListBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearPlPatronList() {
        if (plPatronListBuilder_ == null) {
          plPatronList_ = edu.uconn.guarddogs.guardthebridge.Patron.PatronList.getDefaultInstance();
          onChanged();
        } else {
          plPatronListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronList.Builder getPlPatronListBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getPlPatronListFieldBuilder().getBuilder();
      }
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronListOrBuilder getPlPatronListOrBuilder() {
        if (plPatronListBuilder_ != null) {
          return plPatronListBuilder_.getMessageOrBuilder();
        } else {
          return plPatronList_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          edu.uconn.guarddogs.guardthebridge.Patron.PatronList, edu.uconn.guarddogs.guardthebridge.Patron.PatronList.Builder, edu.uconn.guarddogs.guardthebridge.Patron.PatronListOrBuilder> 
          getPlPatronListFieldBuilder() {
        if (plPatronListBuilder_ == null) {
          plPatronListBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.uconn.guarddogs.guardthebridge.Patron.PatronList, edu.uconn.guarddogs.guardthebridge.Patron.PatronList.Builder, edu.uconn.guarddogs.guardthebridge.Patron.PatronListOrBuilder>(
                  plPatronList_,
                  getParentForChildren(),
                  isClean());
          plPatronList_ = null;
        }
        return plPatronListBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Response)
    }
    
    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Response)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023communication.proto\032\014patron.proto\"\225\001\n\007" +
      "Request\022\016\n\006nReqId\030\001 \002(\005\022\020\n\010sReqType\030\002 \002(" +
      "\t\022\016\n\006nCarId\030\003 \001(\005\022\017\n\007sParams\030\004 \003(\t\022\023\n\007nP" +
      "arams\030\005 \003(\005B\002\020\001\022\017\n\007nClient\030\006 \001(\005\022!\n\014plPa" +
      "tronList\030\007 \001(\0132\013.PatronList\"w\n\010Response\022" +
      "\017\n\007nRespId\030\001 \002(\005\022\021\n\tsResValue\030\002 \002(\t\022\017\n\007s" +
      "ResAdd\030\003 \003(\t\022\023\n\007nResAdd\030\004 \003(\005B\002\020\001\022!\n\014plP" +
      "atronList\030\005 \001(\0132\013.PatronListB$\n\"edu.ucon" +
      "n.guarddogs.guardthebridge"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Request_descriptor,
              new java.lang.String[] { "NReqId", "SReqType", "NCarId", "SParams", "NParams", "NClient", "PlPatronList", },
              edu.uconn.guarddogs.guardthebridge.Communication.Request.class,
              edu.uconn.guarddogs.guardthebridge.Communication.Request.Builder.class);
          internal_static_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Response_descriptor,
              new java.lang.String[] { "NRespId", "SResValue", "SResAdd", "NResAdd", "PlPatronList", },
              edu.uconn.guarddogs.guardthebridge.Communication.Response.class,
              edu.uconn.guarddogs.guardthebridge.Communication.Response.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          edu.uconn.guarddogs.guardthebridge.Patron.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
