// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patron.proto

package edu.uconn.guarddogs.guardthebridge;

public final class Patron {
  private Patron() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PatronInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string name = 1;
    boolean hasName();
    String getName();
    
    // optional uint32 passangers = 2;
    boolean hasPassangers();
    int getPassangers();
    
    // optional string pickup = 3;
    boolean hasPickup();
    String getPickup();
    
    // optional string dropoff = 4;
    boolean hasDropoff();
    String getDropoff();
    
    // optional string phone = 5;
    boolean hasPhone();
    String getPhone();
    
    // optional string status = 6;
    boolean hasStatus();
    String getStatus();
    
    // optional string notes = 7;
    boolean hasNotes();
    String getNotes();
    
    // optional string timetaken = 8;
    boolean hasTimetaken();
    String getTimetaken();
    
    // optional string timeassigned = 9;
    boolean hasTimeassigned();
    String getTimeassigned();
    
    // optional string timedone = 10;
    boolean hasTimedone();
    String getTimedone();
    
    // optional int32 pid = 11;
    boolean hasPid();
    int getPid();
  }
  public static final class PatronInfo extends
      com.google.protobuf.GeneratedMessage
      implements PatronInfoOrBuilder {
    // Use PatronInfo.newBuilder() to construct.
    private PatronInfo(Builder builder) {
      super(builder);
    }
    private PatronInfo(boolean noInit) {}
    
    private static final PatronInfo defaultInstance;
    public static PatronInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public PatronInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.uconn.guarddogs.guardthebridge.Patron.internal_static_PatronInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.uconn.guarddogs.guardthebridge.Patron.internal_static_PatronInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional uint32 passangers = 2;
    public static final int PASSANGERS_FIELD_NUMBER = 2;
    private int passangers_;
    public boolean hasPassangers() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getPassangers() {
      return passangers_;
    }
    
    // optional string pickup = 3;
    public static final int PICKUP_FIELD_NUMBER = 3;
    private java.lang.Object pickup_;
    public boolean hasPickup() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPickup() {
      java.lang.Object ref = pickup_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pickup_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPickupBytes() {
      java.lang.Object ref = pickup_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pickup_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string dropoff = 4;
    public static final int DROPOFF_FIELD_NUMBER = 4;
    private java.lang.Object dropoff_;
    public boolean hasDropoff() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getDropoff() {
      java.lang.Object ref = dropoff_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          dropoff_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDropoffBytes() {
      java.lang.Object ref = dropoff_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        dropoff_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string phone = 5;
    public static final int PHONE_FIELD_NUMBER = 5;
    private java.lang.Object phone_;
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          phone_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string status = 6;
    public static final int STATUS_FIELD_NUMBER = 6;
    private java.lang.Object status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          status_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string notes = 7;
    public static final int NOTES_FIELD_NUMBER = 7;
    private java.lang.Object notes_;
    public boolean hasNotes() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getNotes() {
      java.lang.Object ref = notes_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          notes_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNotesBytes() {
      java.lang.Object ref = notes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        notes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string timetaken = 8;
    public static final int TIMETAKEN_FIELD_NUMBER = 8;
    private java.lang.Object timetaken_;
    public boolean hasTimetaken() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getTimetaken() {
      java.lang.Object ref = timetaken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          timetaken_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimetakenBytes() {
      java.lang.Object ref = timetaken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        timetaken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string timeassigned = 9;
    public static final int TIMEASSIGNED_FIELD_NUMBER = 9;
    private java.lang.Object timeassigned_;
    public boolean hasTimeassigned() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getTimeassigned() {
      java.lang.Object ref = timeassigned_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          timeassigned_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimeassignedBytes() {
      java.lang.Object ref = timeassigned_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        timeassigned_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string timedone = 10;
    public static final int TIMEDONE_FIELD_NUMBER = 10;
    private java.lang.Object timedone_;
    public boolean hasTimedone() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getTimedone() {
      java.lang.Object ref = timedone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          timedone_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimedoneBytes() {
      java.lang.Object ref = timedone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        timedone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 pid = 11;
    public static final int PID_FIELD_NUMBER = 11;
    private int pid_;
    public boolean hasPid() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public int getPid() {
      return pid_;
    }
    
    private void initFields() {
      name_ = "";
      passangers_ = 0;
      pickup_ = "";
      dropoff_ = "";
      phone_ = "";
      status_ = "";
      notes_ = "";
      timetaken_ = "";
      timeassigned_ = "";
      timedone_ = "";
      pid_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, passangers_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPickupBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDropoffBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getPhoneBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getStatusBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getNotesBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getTimetakenBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getTimeassignedBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getTimedoneBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, pid_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, passangers_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPickupBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDropoffBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPhoneBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getStatusBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getNotesBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getTimetakenBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getTimeassignedBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getTimedoneBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, pid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.uconn.guarddogs.guardthebridge.Patron.PatronInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.uconn.guarddogs.guardthebridge.Patron.internal_static_PatronInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.uconn.guarddogs.guardthebridge.Patron.internal_static_PatronInfo_fieldAccessorTable;
      }
      
      // Construct using edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        passangers_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pickup_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        dropoff_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        phone_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        status_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        notes_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        timetaken_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        timeassigned_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        timedone_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.getDescriptor();
      }
      
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo getDefaultInstanceForType() {
        return edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.getDefaultInstance();
      }
      
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo build() {
        edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo buildPartial() {
        edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo result = new edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.passangers_ = passangers_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pickup_ = pickup_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dropoff_ = dropoff_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.phone_ = phone_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.notes_ = notes_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.timetaken_ = timetaken_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.timeassigned_ = timeassigned_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.timedone_ = timedone_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.pid_ = pid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo) {
          return mergeFrom((edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo other) {
        if (other == edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPassangers()) {
          setPassangers(other.getPassangers());
        }
        if (other.hasPickup()) {
          setPickup(other.getPickup());
        }
        if (other.hasDropoff()) {
          setDropoff(other.getDropoff());
        }
        if (other.hasPhone()) {
          setPhone(other.getPhone());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasNotes()) {
          setNotes(other.getNotes());
        }
        if (other.hasTimetaken()) {
          setTimetaken(other.getTimetaken());
        }
        if (other.hasTimeassigned()) {
          setTimeassigned(other.getTimeassigned());
        }
        if (other.hasTimedone()) {
          setTimedone(other.getTimedone());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              passangers_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              pickup_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              dropoff_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              phone_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              status_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              notes_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              timetaken_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              timeassigned_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              timedone_ = input.readBytes();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              pid_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // optional uint32 passangers = 2;
      private int passangers_ ;
      public boolean hasPassangers() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getPassangers() {
        return passangers_;
      }
      public Builder setPassangers(int value) {
        bitField0_ |= 0x00000002;
        passangers_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassangers() {
        bitField0_ = (bitField0_ & ~0x00000002);
        passangers_ = 0;
        onChanged();
        return this;
      }
      
      // optional string pickup = 3;
      private java.lang.Object pickup_ = "";
      public boolean hasPickup() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPickup() {
        java.lang.Object ref = pickup_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pickup_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPickup(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        pickup_ = value;
        onChanged();
        return this;
      }
      public Builder clearPickup() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pickup_ = getDefaultInstance().getPickup();
        onChanged();
        return this;
      }
      void setPickup(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        pickup_ = value;
        onChanged();
      }
      
      // optional string dropoff = 4;
      private java.lang.Object dropoff_ = "";
      public boolean hasDropoff() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getDropoff() {
        java.lang.Object ref = dropoff_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          dropoff_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDropoff(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dropoff_ = value;
        onChanged();
        return this;
      }
      public Builder clearDropoff() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dropoff_ = getDefaultInstance().getDropoff();
        onChanged();
        return this;
      }
      void setDropoff(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        dropoff_ = value;
        onChanged();
      }
      
      // optional string phone = 5;
      private java.lang.Object phone_ = "";
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPhone(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        phone_ = value;
        onChanged();
        return this;
      }
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00000010);
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      void setPhone(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        phone_ = value;
        onChanged();
      }
      
      // optional string status = 6;
      private java.lang.Object status_ = "";
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStatus(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000020);
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      void setStatus(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        status_ = value;
        onChanged();
      }
      
      // optional string notes = 7;
      private java.lang.Object notes_ = "";
      public boolean hasNotes() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getNotes() {
        java.lang.Object ref = notes_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          notes_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNotes(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        notes_ = value;
        onChanged();
        return this;
      }
      public Builder clearNotes() {
        bitField0_ = (bitField0_ & ~0x00000040);
        notes_ = getDefaultInstance().getNotes();
        onChanged();
        return this;
      }
      void setNotes(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        notes_ = value;
        onChanged();
      }
      
      // optional string timetaken = 8;
      private java.lang.Object timetaken_ = "";
      public boolean hasTimetaken() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getTimetaken() {
        java.lang.Object ref = timetaken_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          timetaken_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTimetaken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        timetaken_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimetaken() {
        bitField0_ = (bitField0_ & ~0x00000080);
        timetaken_ = getDefaultInstance().getTimetaken();
        onChanged();
        return this;
      }
      void setTimetaken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        timetaken_ = value;
        onChanged();
      }
      
      // optional string timeassigned = 9;
      private java.lang.Object timeassigned_ = "";
      public boolean hasTimeassigned() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getTimeassigned() {
        java.lang.Object ref = timeassigned_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          timeassigned_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTimeassigned(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        timeassigned_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimeassigned() {
        bitField0_ = (bitField0_ & ~0x00000100);
        timeassigned_ = getDefaultInstance().getTimeassigned();
        onChanged();
        return this;
      }
      void setTimeassigned(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        timeassigned_ = value;
        onChanged();
      }
      
      // optional string timedone = 10;
      private java.lang.Object timedone_ = "";
      public boolean hasTimedone() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getTimedone() {
        java.lang.Object ref = timedone_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          timedone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTimedone(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        timedone_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimedone() {
        bitField0_ = (bitField0_ & ~0x00000200);
        timedone_ = getDefaultInstance().getTimedone();
        onChanged();
        return this;
      }
      void setTimedone(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        timedone_ = value;
        onChanged();
      }
      
      // optional int32 pid = 11;
      private int pid_ ;
      public boolean hasPid() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public int getPid() {
        return pid_;
      }
      public Builder setPid(int value) {
        bitField0_ |= 0x00000400;
        pid_ = value;
        onChanged();
        return this;
      }
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000400);
        pid_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PatronInfo)
    }
    
    static {
      defaultInstance = new PatronInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PatronInfo)
  }
  
  public interface PatronListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .PatronInfo patron = 1;
    java.util.List<edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo> 
        getPatronList();
    edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo getPatron(int index);
    int getPatronCount();
    java.util.List<? extends edu.uconn.guarddogs.guardthebridge.Patron.PatronInfoOrBuilder> 
        getPatronOrBuilderList();
    edu.uconn.guarddogs.guardthebridge.Patron.PatronInfoOrBuilder getPatronOrBuilder(
        int index);
  }
  public static final class PatronList extends
      com.google.protobuf.GeneratedMessage
      implements PatronListOrBuilder {
    // Use PatronList.newBuilder() to construct.
    private PatronList(Builder builder) {
      super(builder);
    }
    private PatronList(boolean noInit) {}
    
    private static final PatronList defaultInstance;
    public static PatronList getDefaultInstance() {
      return defaultInstance;
    }
    
    public PatronList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.uconn.guarddogs.guardthebridge.Patron.internal_static_PatronList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.uconn.guarddogs.guardthebridge.Patron.internal_static_PatronList_fieldAccessorTable;
    }
    
    // repeated .PatronInfo patron = 1;
    public static final int PATRON_FIELD_NUMBER = 1;
    private java.util.List<edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo> patron_;
    public java.util.List<edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo> getPatronList() {
      return patron_;
    }
    public java.util.List<? extends edu.uconn.guarddogs.guardthebridge.Patron.PatronInfoOrBuilder> 
        getPatronOrBuilderList() {
      return patron_;
    }
    public int getPatronCount() {
      return patron_.size();
    }
    public edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo getPatron(int index) {
      return patron_.get(index);
    }
    public edu.uconn.guarddogs.guardthebridge.Patron.PatronInfoOrBuilder getPatronOrBuilder(
        int index) {
      return patron_.get(index);
    }
    
    private void initFields() {
      patron_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < patron_.size(); i++) {
        output.writeMessage(1, patron_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < patron_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, patron_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.uconn.guarddogs.guardthebridge.Patron.PatronList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.uconn.guarddogs.guardthebridge.Patron.PatronList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.uconn.guarddogs.guardthebridge.Patron.PatronListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.uconn.guarddogs.guardthebridge.Patron.internal_static_PatronList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.uconn.guarddogs.guardthebridge.Patron.internal_static_PatronList_fieldAccessorTable;
      }
      
      // Construct using edu.uconn.guarddogs.guardthebridge.Patron.PatronList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPatronFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (patronBuilder_ == null) {
          patron_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          patronBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.uconn.guarddogs.guardthebridge.Patron.PatronList.getDescriptor();
      }
      
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronList getDefaultInstanceForType() {
        return edu.uconn.guarddogs.guardthebridge.Patron.PatronList.getDefaultInstance();
      }
      
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronList build() {
        edu.uconn.guarddogs.guardthebridge.Patron.PatronList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.uconn.guarddogs.guardthebridge.Patron.PatronList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.uconn.guarddogs.guardthebridge.Patron.PatronList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronList buildPartial() {
        edu.uconn.guarddogs.guardthebridge.Patron.PatronList result = new edu.uconn.guarddogs.guardthebridge.Patron.PatronList(this);
        int from_bitField0_ = bitField0_;
        if (patronBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            patron_ = java.util.Collections.unmodifiableList(patron_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.patron_ = patron_;
        } else {
          result.patron_ = patronBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.uconn.guarddogs.guardthebridge.Patron.PatronList) {
          return mergeFrom((edu.uconn.guarddogs.guardthebridge.Patron.PatronList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.uconn.guarddogs.guardthebridge.Patron.PatronList other) {
        if (other == edu.uconn.guarddogs.guardthebridge.Patron.PatronList.getDefaultInstance()) return this;
        if (patronBuilder_ == null) {
          if (!other.patron_.isEmpty()) {
            if (patron_.isEmpty()) {
              patron_ = other.patron_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePatronIsMutable();
              patron_.addAll(other.patron_);
            }
            onChanged();
          }
        } else {
          if (!other.patron_.isEmpty()) {
            if (patronBuilder_.isEmpty()) {
              patronBuilder_.dispose();
              patronBuilder_ = null;
              patron_ = other.patron_;
              bitField0_ = (bitField0_ & ~0x00000001);
              patronBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPatronFieldBuilder() : null;
            } else {
              patronBuilder_.addAllMessages(other.patron_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.Builder subBuilder = edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPatron(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .PatronInfo patron = 1;
      private java.util.List<edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo> patron_ =
        java.util.Collections.emptyList();
      private void ensurePatronIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          patron_ = new java.util.ArrayList<edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo>(patron_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo, edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.Builder, edu.uconn.guarddogs.guardthebridge.Patron.PatronInfoOrBuilder> patronBuilder_;
      
      public java.util.List<edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo> getPatronList() {
        if (patronBuilder_ == null) {
          return java.util.Collections.unmodifiableList(patron_);
        } else {
          return patronBuilder_.getMessageList();
        }
      }
      public int getPatronCount() {
        if (patronBuilder_ == null) {
          return patron_.size();
        } else {
          return patronBuilder_.getCount();
        }
      }
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo getPatron(int index) {
        if (patronBuilder_ == null) {
          return patron_.get(index);
        } else {
          return patronBuilder_.getMessage(index);
        }
      }
      public Builder setPatron(
          int index, edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo value) {
        if (patronBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePatronIsMutable();
          patron_.set(index, value);
          onChanged();
        } else {
          patronBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPatron(
          int index, edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.Builder builderForValue) {
        if (patronBuilder_ == null) {
          ensurePatronIsMutable();
          patron_.set(index, builderForValue.build());
          onChanged();
        } else {
          patronBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPatron(edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo value) {
        if (patronBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePatronIsMutable();
          patron_.add(value);
          onChanged();
        } else {
          patronBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPatron(
          int index, edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo value) {
        if (patronBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePatronIsMutable();
          patron_.add(index, value);
          onChanged();
        } else {
          patronBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPatron(
          edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.Builder builderForValue) {
        if (patronBuilder_ == null) {
          ensurePatronIsMutable();
          patron_.add(builderForValue.build());
          onChanged();
        } else {
          patronBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPatron(
          int index, edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.Builder builderForValue) {
        if (patronBuilder_ == null) {
          ensurePatronIsMutable();
          patron_.add(index, builderForValue.build());
          onChanged();
        } else {
          patronBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPatron(
          java.lang.Iterable<? extends edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo> values) {
        if (patronBuilder_ == null) {
          ensurePatronIsMutable();
          super.addAll(values, patron_);
          onChanged();
        } else {
          patronBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPatron() {
        if (patronBuilder_ == null) {
          patron_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          patronBuilder_.clear();
        }
        return this;
      }
      public Builder removePatron(int index) {
        if (patronBuilder_ == null) {
          ensurePatronIsMutable();
          patron_.remove(index);
          onChanged();
        } else {
          patronBuilder_.remove(index);
        }
        return this;
      }
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.Builder getPatronBuilder(
          int index) {
        return getPatronFieldBuilder().getBuilder(index);
      }
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronInfoOrBuilder getPatronOrBuilder(
          int index) {
        if (patronBuilder_ == null) {
          return patron_.get(index);  } else {
          return patronBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends edu.uconn.guarddogs.guardthebridge.Patron.PatronInfoOrBuilder> 
           getPatronOrBuilderList() {
        if (patronBuilder_ != null) {
          return patronBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(patron_);
        }
      }
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.Builder addPatronBuilder() {
        return getPatronFieldBuilder().addBuilder(
            edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.getDefaultInstance());
      }
      public edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.Builder addPatronBuilder(
          int index) {
        return getPatronFieldBuilder().addBuilder(
            index, edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.getDefaultInstance());
      }
      public java.util.List<edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.Builder> 
           getPatronBuilderList() {
        return getPatronFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo, edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.Builder, edu.uconn.guarddogs.guardthebridge.Patron.PatronInfoOrBuilder> 
          getPatronFieldBuilder() {
        if (patronBuilder_ == null) {
          patronBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo, edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.Builder, edu.uconn.guarddogs.guardthebridge.Patron.PatronInfoOrBuilder>(
                  patron_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          patron_ = null;
        }
        return patronBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:PatronList)
    }
    
    static {
      defaultInstance = new PatronList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PatronList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PatronInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PatronInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PatronList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PatronList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014patron.proto\"\305\001\n\nPatronInfo\022\014\n\004name\030\001 " +
      "\001(\t\022\022\n\npassangers\030\002 \001(\r\022\016\n\006pickup\030\003 \001(\t\022" +
      "\017\n\007dropoff\030\004 \001(\t\022\r\n\005phone\030\005 \001(\t\022\016\n\006statu" +
      "s\030\006 \001(\t\022\r\n\005notes\030\007 \001(\t\022\021\n\ttimetaken\030\010 \001(" +
      "\t\022\024\n\014timeassigned\030\t \001(\t\022\020\n\010timedone\030\n \001(" +
      "\t\022\013\n\003pid\030\013 \001(\005\")\n\nPatronList\022\033\n\006patron\030\001" +
      " \003(\0132\013.PatronInfoB$\n\"edu.uconn.guarddogs" +
      ".guardthebridge"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PatronInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PatronInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PatronInfo_descriptor,
              new java.lang.String[] { "Name", "Passangers", "Pickup", "Dropoff", "Phone", "Status", "Notes", "Timetaken", "Timeassigned", "Timedone", "Pid", },
              edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.class,
              edu.uconn.guarddogs.guardthebridge.Patron.PatronInfo.Builder.class);
          internal_static_PatronList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PatronList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PatronList_descriptor,
              new java.lang.String[] { "Patron", },
              edu.uconn.guarddogs.guardthebridge.Patron.PatronList.class,
              edu.uconn.guarddogs.guardthebridge.Patron.PatronList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
